apiVersion: v1

kind: Secret


metadata:

  name: users-secret


type: Opaque


stringData:


  SA_PASSWORD: "Sql@123456789"


  ConnectionStrings__DefaultConnection: "Server=users-db;Database=Usuarios;User Id=sa;Password=Sql@123456789;TrustServerCertificate=True"


  Jwt__Key: "uma-chave-grande-e-secreta-para-jwt"


  RabbitMQ__Username: "fcgrabbtmq"


  RabbitMQ__Password: "fcgrabbtmq"